"""
Django settings for comparateur_allemand project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-a(zv&+8n_s)c)pzdi8!!mwkc60=cyup9xemwwr%5pso)0u!)xa')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'products',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'comparateur_allemand.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'comparateur_allemand.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}

# MongoDB Configuration
import mongoengine

def _get_mongodb_uri(host, port, db_name, username, password, auth_source):
    """Build MongoDB URI for both Atlas and standard connections"""
    if username and password:
        # For MongoDB Atlas: use mongodb+srv:// protocol
        if ':' not in host and int(port) == 27017:
            # This is likely MongoDB Atlas
            uri = f"mongodb+srv://{username}:{password}@{host}/{db_name}?authSource={auth_source}&retryWrites=true"
        else:
            # Standard MongoDB connection
            uri = f"mongodb://{username}:{password}@{host}:{port}/{db_name}?authSource={auth_source}&retryWrites=true"
        return uri
    else:
        return f"mongodb://{host}:{port}/{db_name}"

# Saturn Database Connection
SATURN_URI = _get_mongodb_uri(
    host=os.getenv('SATURN_MONGODB_HOST', 'cluster0.pzd9gka.mongodb.net'),
    port=int(os.getenv('SATURN_MONGODB_PORT', 27017)),
    db_name=os.getenv('SATURN_MONGODB_DB_NAME', 'Saturn'),
    username=os.getenv('MONGODB_USER', None),
    password=os.getenv('MONGODB_PASSWORD', None),
    auth_source=os.getenv('MONGODB_AUTH_SOURCE', 'admin'),
)

# MediaMarkt Database Connection
MEDIAMARKT_URI = _get_mongodb_uri(
    host=os.getenv('MEDIAMARKT_MONGODB_HOST', 'mediamarkt.iwjamu6.mongodb.net'),
    port=int(os.getenv('MEDIAMARKT_MONGODB_PORT', 27017)),
    db_name=os.getenv('MEDIAMARKT_MONGODB_DB_NAME', 'mediamarkt'),
    username=os.getenv('MONGODB_USER', None),
    password=os.getenv('MONGODB_PASSWORD', None),
    auth_source=os.getenv('MONGODB_AUTH_SOURCE', 'admin'),
)

# Initialize MongoDB connections
try:
    # Disconnect any existing connections first
    mongoengine.disconnect()
except:
    pass

try:
    # Saturn connection (default)
    mongoengine.connect(
        'default',
        host=SATURN_URI,
        connectTimeoutMS=5000,
        serverSelectionTimeoutMS=5000,
    )
    print("Saturn database connected successfully")
except Exception as e:
    print(f"Warning: Saturn database connection failed: {e}")

try:
    # MediaMarkt connection
    mongoengine.connect(
        'mediamarkt',
        host=MEDIAMARKT_URI,
        connectTimeoutMS=5000,
        serverSelectionTimeoutMS=5000,
    )
    print("MediaMarkt database connected successfully")
except Exception as e:
    print(f"Warning: MediaMarkt database connection failed: {e}")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'public', 'static')

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'public', 'media')

# Ensure directories exist
os.makedirs(STATIC_ROOT, exist_ok=True)
os.makedirs(MEDIA_ROOT, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:3001',
    cast=Csv()
)

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# Security Settings for Production
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': config('LOG_LEVEL', default='INFO'),
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'preisradio.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'level': config('LOG_LEVEL', default='INFO'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': config('LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'products': {
            'handlers': ['console', 'file'],
            'level': config('LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)