"""
Django settings for comparateur_allemand project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see    
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-a(zv&+8n_s)c)pzdi8!!mwkc60=cyup9xemwwr%5pso)0u!)xa')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,api.preisradio.de', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'products',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'comparateur_allemand.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'comparateur_allemand.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy',
    }
}

# MongoDB Configuration
import mongoengine

# Get MongoDB URIs and database names from environment variables
# Saturn Database Configuration
SATURN_URI = os.getenv('MONGODB_SATURN_URI', 'mongodb+srv://stronglimitless76_db_user:XkH6zK9tcANup38i@cluster0.pzd9gka.mongodb.net/')
SATURN_DB = os.getenv('MONGODB_SATURN_DB', 'Saturn')
SATURN_COLLECTION = os.getenv('MONGODB_SATURN_COLLECTION', 'Db')

# MediaMarkt Database Configuration
MEDIAMARKT_URI = os.getenv('MONGODB_MEDIAMARKT_URI', 'mongodb+srv://stronglimitless76_db_user:oLZm2SKrgK5ZskXv@mediamarkt.iwjamu6.mongodb.net/')
MEDIAMARKT_DB = os.getenv('MONGODB_MEDIAMARKT_DB', 'Mediamarkt')
MEDIAMARKT_COLLECTION = os.getenv('MONGODB_MEDIAMARKT_COLLECTION', 'Db')

# Otto Database Configuration
OTTO_URI = os.getenv('MONGODB_OTTO_URI', 'mongodb+srv://stronglimitless76_db_user:ThiKAzVAqh0fmbtS@otto.sx1z58n.mongodb.net/')
OTTO_DB = os.getenv('MONGODB_OTTO_DB', 'Otto')
OTTO_COLLECTION = os.getenv('MONGODB_OTTO_COLLECTION', 'Db')

# Build full URIs with database names
SATURN_FULL_URI = f"{SATURN_URI}{SATURN_DB}?retryWrites=true&w=majority"
MEDIAMARKT_FULL_URI = f"{MEDIAMARKT_URI}{MEDIAMARKT_DB}?retryWrites=true&w=majority"
OTTO_FULL_URI = f"{OTTO_URI}{OTTO_DB}?retryWrites=true&w=majority"

# Print configuration for debugging
print(f"📊 MongoDB Configuration:")
print(f"   Saturn DB: {SATURN_DB}, Collection: {SATURN_COLLECTION}")
print(f"   MediaMarkt DB: {MEDIAMARKT_DB}, Collection: {MEDIAMARKT_COLLECTION}")
print(f"   Otto DB: {OTTO_DB}, Collection: {OTTO_COLLECTION}")

# Initialize MongoDB connections
# Disconnect existing connections to avoid duplicate registration errors
try:
    mongoengine.disconnect(alias='default')
except:
    pass

try:
    mongoengine.disconnect(alias='mediamarkt')
except:
    pass

try:
    mongoengine.disconnect(alias='otto')
except:
    pass

# Connect to Saturn database
try:
    mongoengine.connect(
        alias='default',
        host=SATURN_FULL_URI,
        connectTimeoutMS=30000,
        serverSelectionTimeoutMS=30000,
        socketTimeoutMS=30000,
        maxPoolSize=100,
    )
    print("✓ Saturn database connected successfully")
except Exception as e:
    print(f"✗ Saturn database connection failed: {e}")

# Connect to MediaMarkt database
try:
    mongoengine.connect(
        alias='mediamarkt',
        host=MEDIAMARKT_FULL_URI,
        connectTimeoutMS=30000,
        serverSelectionTimeoutMS=30000,
        socketTimeoutMS=30000,
        maxPoolSize=100,
    )
    print("✓ MediaMarkt database connected successfully")
except Exception as e:
    print(f"✗ MediaMarkt database connection failed: {e}")

# Connect to Otto database
try:
    mongoengine.connect(
        alias='otto',
        host=OTTO_FULL_URI,
        connectTimeoutMS=30000,
        serverSelectionTimeoutMS=30000,
        socketTimeoutMS=30000,
        maxPoolSize=100,
        tls=True,
        tlsAllowInvalidCertificates=True,  # Workaround for SSL issues on serv00
    )
    print("✓ Otto database connected successfully")
except Exception as e:
    print(f"✗ Otto database connection failed: {e}")


# Google Merchant Center Configuration
GOOGLE_MERCHANT_ID = config('GOOGLE_MERCHANT_ID', default='')
GOOGLE_SERVICE_ACCOUNT_KEY = os.path.join(BASE_DIR.parent, 'astute-pride-262723-7f9bd77e07a5.json')


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'public', 'static')

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'public', 'media')

# Ensure directories exist
os.makedirs(STATIC_ROOT, exist_ok=True)
os.makedirs(MEDIA_ROOT, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:3001',
    cast=Csv()
)

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'MAX_PAGE_SIZE': 10000,  # Allow up to 10000 items per page for sitemap generation
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# Security Settings for Production
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': config('LOG_LEVEL', default='INFO'),
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'preisradio.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
            'level': config('LOG_LEVEL', default='INFO'),
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': config('LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'products': {
            'handlers': ['console', 'file'],
            'level': config('LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

# Email Configuration - serv00 SMTP settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='mail11.serv00.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='preisradio@preisradio.de')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='preisradio@preisradio.de')
CONTACT_EMAIL = config('CONTACT_EMAIL', default='team_preisradio@wael.serv00.net')